blank_issues_enabled: false
contact_links:
  - name: Security issue (private)
    url: https://github.com/RAY-Group-eu/JobBridge/security/advisories/new
    about: Sicherheitslücken bitte privat melden (keine Details in öffentlichen Issues).
